
language: c

env:
  - XCC=clang HOST= WINE=
  - XCC=gcc HOST= WINE=
  - XCC=i686-w64-mingw32-gcc HOST="--host=i686-w64-mingw32" WINE=wine
  - XCC=x86_64-w64-mingw32-gcc HOST="--host=x86_64-w64-mingw32" WINE=wine64
  - XCC=gcc HOST= WINE= GCOV="--enable-gcov"

before_install:
  - "sudo apt-get -qq update --force-yes > /dev/null"
  - "if [ x$WINE = x ]; then sudo apt-get install -qq valgrind > /dev/null; fi"
  - "if [ x$WINE != x ]; then sudo apt-get install -qq wine > /dev/null; fi"
  - "if [ x$XCC = xclang ]; then sudo apt-get install -qq clang; fi"
  - "if [ x$XCC = xgcc ]; then sudo apt-get install -qq gcc; fi"
  - "if [ x$XCC = xi686-w64-mingw32-gcc ]; then sudo apt-get install -qq gcc-mingw-w64-i686 binutils-mingw-w64-i686; fi"
  - "if [ x$XCC = xx86_64-w64-mingw32-gcc ]; then sudo apt-get install -qq gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64; fi"
  - "if [ x$GCOV != x ]; then sudo apt-get install libyaml-dev; fi"
  - "if [ x$GCOV != x ]; then sudo pip install cpp-coveralls pyyaml; fi"

before_script:
  - "CC=$XCC ./configure --prefix=/usr ${HOST} ${GCOV}"

script:
  - "make"
  - "sudo make install"
  - "$WINE seq2gif --version"
  - "if [ x$GCOV != x ]; then make coveralls || exit 1; fi"

after_success:
  - "if [ x$WINE = x ]; then make valgrind && exit 0 || cat valgrind.log && exit 1; fi"
